name: Playwright Tests
on:
  deployment_status:

jobs:
  test:
   # We deploy multiple sites from main branch, which makes the setup quite tricky.
    # So we're only testing on The Good News Room deployments in Pull Requests, which should be enough.
    if: >-
      !contains(fromJSON('["Production – theme-nextjs-starter-cookbook", "Production – theme-nextjs-starter-photography", "Production – theme-nextjs-starter-preview", "Production – theme-nextjs-starter-the-good-newsroom"]'), github.event.deployment.environment)
    uses: prezly/theme-kit-js/.github/workflows/playwright.shared.yml@main
    with:
      site-name: 'The Good News Room'
